language: julia
os:
  - linux
  - osx
julia:
  - 0.3
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.add("HTTPClient"); Pkg.add("JSON"); Pkg.build("ConnectSDK"); Pkg.test("ConnectSDK"; coverage=true)'
